---
# tasks file for ansible-role-idp
- name: Start docker container
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: szabogyula/test-saml-idp
    state: started
    pull: true
    restart: true
    restart_policy: unless-stopped
    env:
      VIRTUAL_HOST: "{{ VIRTUAL_HOST }}"
      LETSENCRYPT_HOST: "{{ VIRTUAL_HOST }}"
      MDX_URL:      "{{ MDX_URL }}"
      SIMPLESAMLPHP_ADMIN_PASSWORD: "{{ SIMPLESAMLPHP_ADMIN_PASSWORD }}"
      SIMPLESAMLPHP_SECRET_SALT:    "{{ SIMPLESAMLPHP_SECRET_SALT }}"

    labels: "{{ LABELS }}"
  tags:
    - idp
